///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace TestGitMerge
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the TestGitMergeRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
    [RepositoryFolder("81d402c7-c59d-464e-a5da-f40010fb3e89")]
    public partial class TestGitMergeRepository : RepoGenBaseFolder
    {
        static TestGitMergeRepository instance = new TestGitMergeRepository();

        /// <summary>
        /// Gets the singleton class instance representing the TestGitMergeRepository element repository.
        /// </summary>
        [RepositoryFolder("81d402c7-c59d-464e-a5da-f40010fb3e89")]
        public static TestGitMergeRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public TestGitMergeRepository() 
            : base("TestGitMergeRepository", "/", null, 0, false, "81d402c7-c59d-464e-a5da-f40010fb3e89", ".\\RepositoryImages\\TestGitMergeRepository81d402c7.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("81d402c7-c59d-464e-a5da-f40010fb3e89")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
    public partial class TestGitMergeRepositoryFolders
    {
    }
#pragma warning restore 0436
}